apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-prod
  namespace: observability
spec:
  strategy: production
  storage:
      type: elasticsearch
      options:
        es:
          server-urls: http://elasticsearch-master.default.svc.cluster.local:9200

  collector:
    maxReplicas: 1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
